/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test 
    void testMethodAlwaysReturnsTrue() {
        Algorithm classUnderTest = new Algorithm();
        assertTrue(classUnderTest.returnTrue(), "someLibraryMethod should return 'true'");
    }

    @Test 
    void testCountPlacementsForSmallBoardSizes() {
        assertEquals(1, Algorithm.countPlacements(1));
        assertEquals(6, Algorithm.countPlacements(2));
        assertEquals(84, Algorithm.countPlacements(3));
        assertEquals(1820, Algorithm.countPlacements(4));
        assertEquals(53130, Algorithm.countPlacements(5));
        assertEquals(1947792, Algorithm.countPlacements(6));
        assertEquals(85900584, Algorithm.countPlacements(7));
        assertEquals( 4426165368L, Algorithm.countPlacements(8));
    }

    @Test 
    void testFastCountPlacementsForSmallBoardSizes() {
        assertEquals(1, Algorithm.fastCountPlacements(1));
        assertEquals(6, Algorithm.fastCountPlacements(2));
        assertEquals(84, Algorithm.fastCountPlacements(3));
        assertEquals(1820, Algorithm.fastCountPlacements(4));
        assertEquals(53130, Algorithm.fastCountPlacements(5));
        assertEquals(1947792, Algorithm.fastCountPlacements(6));
        assertEquals(85900584, Algorithm.fastCountPlacements(7));
        assertEquals(4426165368L, Algorithm.fastCountPlacements(8));
    }

     @Test
    public void testGeneratePlacementsHasCorrectSizeForSmallBoardSizes() {
        assertEquals(1, Algorithm.generatePlacements(1).size());
        assertEquals(6, Algorithm.generatePlacements(2).size());
        assertEquals(84, Algorithm.generatePlacements(3).size());
        assertEquals(1820, Algorithm.generatePlacements(4).size());
        assertEquals(53130, Algorithm.generatePlacements(5).size());
        assertEquals(1947792, Algorithm.generatePlacements(6).size());
        assertEquals(85900584, Algorithm.generatePlacements(7).size());
    }
}
